# Generated by Django 4.1.7 on 2023-11-23 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=300)),
                ('commodity', models.CharField(max_length=300)),
                ('commission_agent', models.CharField(max_length=300)),
                ('quote', models.CharField(max_length=300)),
                ('quality', models.CharField(max_length=300)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
