# Generated by Django 4.1.7 on 2023-11-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_passwordreset_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='user',
            new_name='user_id',
        ),
    ]
