# Generated by Django 4.1.7 on 2023-11-24 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_apmc_operator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apmc',
            name='operator_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
