# Generated by Django 4.1.7 on 2023-11-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_apmc_operator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apmc',
            name='operator_id',
        ),
    ]
