# Generated by Django 4.1.7 on 2023-11-27 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_apmc_operator_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='APMCTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=300)),
                ('commission_agent', models.CharField(max_length=300)),
                ('lot_id', models.CharField(max_length=100)),
                ('Bags', models.IntegerField()),
                ('lot_code', models.CharField(max_length=300)),
                ('quality', models.CharField(max_length=200)),
                ('rs', models.IntegerField()),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('operator_id', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
