# Generated by Django 4.2.6 on 2024-02-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apmcetender',
            name='rs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='apmctender',
            name='rs',
            field=models.FloatField(),
        ),
    ]
